name: "Build and publish"
on:
  workflow_run:
    workflows: [ "Release" ]
    branches: [ "main" ]
    types:
      - completed
jobs:
  build-publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - run: 'echo "Would publish version $(cat version)"'
