name: Build and Publish
run-name: "Build and Publish: ${{ github.event.head_commit.message }}"
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
      - run: 'echo "Would publish version ${{ inputs.tag }}"'