name: "Build and publish"
on:
  release:
    types:
      - created
jobs:
  build-publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.release.draft == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - run: 'echo "Would publish version $(cat version)"'
