name: "On Push To Main"
run-name: "On Push To Main: ${{ github.event.head_commit.message }}"
on:
  push:
    branches: [ "main" ]

jobs:
  test:
    uses: ./.github/workflows/test.yml
  read-version-and-tag-exists:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - id: version
        run: |
          version=$(cat version)
          echo version=$version
          echo version=$version >> $GITHUB_OUTPUT
      - id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.0.0
      - id: matches
        run: |
          echo matches=$([[ "${{ steps.previoustag.outputs.tag }}" == "${{ steps.version.outputs.version }}" ]] && echo "true" || echo "false") >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag_exists: ${{ steps.mathces.outputs.matches }}
  tag-and-release:
    permissions:
      contents: write
    needs:
      - read-version-and-tag-exists
    if: needs.read-version-and-tag-exists.outputs.tag_exists == 'false'
    uses: ./.github/workflows/tag-and-release.yml
    with:
      tag: ${{ needs.read-version-and-tag-exists.outputs.version }}
  build-and-publish:
    needs: 
      - tag-and-release
    uses: ./.github/workflows/build-and-publish.yml
    with:
      tag: ${{ needs.tag-and-release.outputs.tag }}