name: "On Push To Main"
run-name: "On Push To Main: ${{ github.event.head_commit.message }}"
on:
  push:
    branches: [ "main" ]

jobs:
  test:
    uses: ./.github/workflows/test.yml
  read-version-and-tag-exists:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4  
      - id: read_version
        run: |
          version=$(cat version)
          echo version=$version
          echo version=$version >> $GITHUB_OUTPUT
          tag_exists=$(git tag | grep -qE ^$version$ && echo "true" || echo "false")
          echo tag_exists=$tag_exists
          echo tag_exists=$tag_exists >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.read_version.outputs.version }}
      tag_exists: ${{ steps.read_version.outputs.tag_exists }}
  tag-and-release:
    permissions:
      contents: write
    needs:
      - read-version-and-tag-exists
    if: needs.read-version-and-tag-exists.outputs.tag_exists == 'false'
    uses: ./.github/workflows/tag-and-release.yml
    with:
      tag: ${{ needs.read-version-and-tag-exists.outputs.version }}
  build-and-publish:
    needs: 
      - tag-and-release
    uses: ./.github/workflows/build-and-publish.yml
    with:
      tag: ${{ needs.tag-and-release.outputs.tag }}