name: Release
run-name: "Release: ${{ github.event.workflow_run.jobs.tag.outputs.tag }}"
on:
  workflow_run:
    workflows: [ "Tag" ]
    branches: [ "main" ]
    types:
      - completed

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ github.event.workflow_run.jobs.tag.outputs.tag }}
    outputs:
      name: ${{ github.event.workflow_run.jobs.tag.outputs.tag }}

