name: Release
on:
  workflow_run:
    workflows: [ "Test" ]
    branches: [ "main" ]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4  
      - id: read_version
        run: 'VERSION=$(cat version) >> $GITHUB_OUTPUT'
      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.read_version.outputs.VERSION }}
          tag_name: ${{ steps.read_version.outputs.VERSION }}
          draft: true
          make_latest: true
          generate_release_notes: true

