name: Release
on: push

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - id: read_version
        run: 'VERSION=$(cat version) >> $GITHUB_OUTPUT'
      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          custom_tag: ${{ steps.read_version.outputs.VERSION }}
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          generate_release_notes: true

