# name: Release
# run-name: "Release: ${{ github.event.workflow_run.head_commit.message }}"
# on:
#   workflow_run:
#     workflows: [ "Test" ]
#     branches: [ "main" ]
#     types:
#       - completed

# jobs:
#   tag:
#     permissions:
#       contents: write
#     runs-on: ubuntu-latest
#     if: github.event.workflow_run.conclusion == 'success'
#     steps:
#       - name: Dump GitHub context
#         env:
#           GITHUB_CONTEXT: ${{ toJson(github) }}
#         run: |
#           echo "$GITHUB_CONTEXT"
#       - uses: actions/checkout@v4  
#       - id: read_version
#         run: |
#           VERSION=$(cat version)
#           echo VERSION=$VERSION >> $GITHUB_OUTPUT'
#           echo TAG_EXISTS=$(git tag | grep -qE ^$VERSION$ && echo "true" || echo "false") >> $GITHUB_OUTPUT'
#       - name: Push tag
#         if: steps.read_version.outputs.TAG_EXISTS == 'false'
#         id: tag
#         uses: mathieudutour/github-tag-action@v6.2
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           tag_prefix: ''
#           custom_tag: ${{ steps.read_version.outputs.VERSION }}
#     outputs:
#       tag: ${{ steps.tag.outputs.new_tag }}
#       skip: ${{ steps.read_version.outputs.TAG_EXISTS }}
#   release:
#     needs:
#       - tag
#     if: needs.tag.outputs.skip == 'false'
#     permissions:
#       contents: write
#     runs-on: ubuntu-latest
#     steps:
#       - name: Dump Needs context
#         env:
#           NEEDS_CONTEXT: ${{ toJson(needs) }}
#         run: |
#           echo "$NEEDS_CONTEXT"
#       - name: Dump GitHub context
#         env:
#           GITHUB_CONTEXT: ${{ toJson(github) }}
#         run: |
#           echo "$GITHUB_CONTEXT"
#       - uses: softprops/action-gh-release@v2
#         with:
#           generate_release_notes: true
#           tag_name: ${{ needs.tag.outputs.tag }}
#     outputs:
#       release: ${{ needs.tag.outputs.tag }}
#   build-publish:
#     needs:
#       - release
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - run: 'echo "Would publish version ${{ needs.release.outputs.name }}"'

