name: Release
on:
  push: 
    tags:
      - "*"

jobs:
  release:

    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - id: read_version
        run: 'VERSION=$(cat version) >> $GITHUB_OUTPUT'
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

