name: Tag and Release
run-name: "Tag and Release: ${{ github.event.head_commit.message }}"
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    outputs:
      tag:
        value: ${{ jobs.tag.outputs.tag }}

jobs:
  tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Push tag
        if: steps.read_version.outputs.TAG_EXISTS == 'false'
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
          custom_tag: ${{ inputs.tag }}
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
  release:
    needs:
      - tag
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ needs.tag.outputs.tag }}