name: Tag
on:
  workflow_run:
    workflows: [ "Test" ]
    branches: [ "main" ]
    types:
      - completed

jobs:
  tag:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4  
      - id: read_version
        run: 'VERSION=$(cat version) >> $GITHUB_OUTPUT'
      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          custom_tag: ${{ steps.read_version.outputs.VERSION }}

