name: Tag
run-name: "Tag: ${{ github.event.head_commit.message }}"
on:
  workflow_run:
    workflows: [ "Test" ]
    branches: [ "main" ]
    types:
      - completed

jobs:
  tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v4  
      - id: read_version
        run: 'echo VERSION=$(cat version) >> $GITHUB_OUTPUT'
      - run: 'echo ${{ steps.read_version.outputs.VERSION }}'
      - name: Push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.read_version.outputs.VERSION }}
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}

