name: Test
run-name: "Test: ${{ github.event.head_commit.message }}"
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: '[[ "$(cat test)" == "pass" ]]'